name: Build STM32H743 CMake Template

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install gcc-arm-none-eabi -y

      - name: CMake configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build

      - name: Build
        run: cmake --build build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: STM32H743-CMake-Template-Artifacts
          path: build/STM32H743-CMake-Template*
